# Generated by Django 3.2.6 on 2021-08-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nba_players_21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, verbose_name='full_name')),
                ('team', models.CharField(max_length=3, verbose_name='team')),
                ('position', models.CharField(max_length=15, verbose_name='position')),
                ('age', models.FloatField(blank=True, null=True, verbose_name='age')),
                ('gp', models.FloatField(blank=True, null=True, verbose_name='gp')),
                ('mpg', models.FloatField(blank=True, null=True, verbose_name='mpg')),
                ('minP', models.FloatField(blank=True, null=True, verbose_name='min%')),
                ('usage', models.FloatField(blank=True, null=True, verbose_name='usage%')),
                ('toRate', models.FloatField(blank=True, null=True, verbose_name='to rate')),
                ('fta', models.FloatField(blank=True, null=True, verbose_name='fta')),
                ('ftP', models.FloatField(blank=True, null=True, verbose_name='ft%')),
                ('fga2', models.FloatField(blank=True, null=True, verbose_name='fga2')),
                ('fga2P', models.FloatField(blank=True, null=True, verbose_name='fga2%')),
                ('fga3', models.FloatField(blank=True, null=True, verbose_name='fga3')),
                ('fga3P', models.FloatField(blank=True, null=True, verbose_name='fga3%')),
                ('efg', models.FloatField(blank=True, null=True, verbose_name='efg')),
                ('ts', models.FloatField(blank=True, null=True, verbose_name='ts')),
                ('ppg', models.FloatField(blank=True, null=True, verbose_name='ppg')),
                ('rpg', models.FloatField(blank=True, null=True, verbose_name='rpg')),
                ('trbP', models.FloatField(blank=True, null=True, verbose_name='trb%')),
                ('apg', models.FloatField(blank=True, null=True, verbose_name='apg')),
                ('astP', models.FloatField(blank=True, null=True, verbose_name='ast%')),
                ('spg', models.FloatField(blank=True, null=True, verbose_name='spg')),
                ('bpg', models.FloatField(blank=True, null=True, verbose_name='bpg')),
                ('topg', models.FloatField(blank=True, null=True, verbose_name='topg')),
                ('viv', models.FloatField(blank=True, null=True, verbose_name='viv')),
                ('ortg', models.FloatField(blank=True, null=True, verbose_name='ortg')),
                ('drtg', models.FloatField(blank=True, null=True, verbose_name='drtg')),
            ],
        ),
    ]
