# Generated by Django 3.2.6 on 2021-10-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nba_players_20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='full_name')),
                ('team', models.CharField(max_length=5, verbose_name='team')),
                ('position', models.CharField(max_length=15, verbose_name='position')),
                ('age', models.FloatField(blank=True, verbose_name='age')),
                ('gp', models.IntegerField(blank=True, verbose_name='gp')),
                ('mpg', models.FloatField(blank=True, verbose_name='mpg')),
                ('minP', models.FloatField(blank=True, verbose_name='min%')),
                ('usage', models.FloatField(blank=True, verbose_name='usage%')),
                ('toRate', models.FloatField(blank=True, verbose_name='to rate')),
                ('fta', models.IntegerField(blank=True, verbose_name='fta')),
                ('ftP', models.FloatField(blank=True, verbose_name='ft%')),
                ('fga2', models.IntegerField(blank=True, verbose_name='fga2')),
                ('fga2P', models.FloatField(blank=True, verbose_name='fga2%')),
                ('fga3', models.IntegerField(blank=True, verbose_name='fga3')),
                ('fga3P', models.FloatField(blank=True, verbose_name='fga3%')),
                ('efg', models.FloatField(blank=True, verbose_name='efg')),
                ('ts', models.FloatField(blank=True, verbose_name='ts')),
                ('ppg', models.FloatField(blank=True, verbose_name='ppg')),
                ('rpg', models.FloatField(blank=True, verbose_name='rpg')),
                ('trbP', models.FloatField(blank=True, verbose_name='trb%')),
                ('apg', models.FloatField(blank=True, verbose_name='apg')),
                ('astP', models.FloatField(blank=True, verbose_name='ast%')),
                ('spg', models.FloatField(blank=True, verbose_name='spg')),
                ('bpg', models.FloatField(blank=True, verbose_name='bpg')),
                ('topg', models.FloatField(blank=True, verbose_name='topg')),
                ('viv', models.FloatField(blank=True, verbose_name='viv')),
                ('ortg', models.FloatField(blank=True, verbose_name='ortg')),
                ('drtg', models.FloatField(blank=True, verbose_name='drtg')),
            ],
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='age',
            field=models.FloatField(blank=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='apg',
            field=models.FloatField(blank=True, verbose_name='apg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='astP',
            field=models.FloatField(blank=True, verbose_name='ast%'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='bpg',
            field=models.FloatField(blank=True, verbose_name='bpg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='drtg',
            field=models.FloatField(blank=True, verbose_name='drtg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='efg',
            field=models.FloatField(blank=True, verbose_name='efg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='fga2',
            field=models.IntegerField(blank=True, verbose_name='fga2'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='fga2P',
            field=models.FloatField(blank=True, verbose_name='fga2%'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='fga3',
            field=models.IntegerField(blank=True, verbose_name='fga3'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='fga3P',
            field=models.FloatField(blank=True, verbose_name='fga3%'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='ftP',
            field=models.FloatField(blank=True, verbose_name='ft%'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='fta',
            field=models.IntegerField(blank=True, verbose_name='fta'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='fullName',
            field=models.CharField(max_length=100, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='gp',
            field=models.IntegerField(blank=True, verbose_name='gp'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='minP',
            field=models.FloatField(blank=True, verbose_name='min%'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='mpg',
            field=models.FloatField(blank=True, verbose_name='mpg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='ortg',
            field=models.FloatField(blank=True, verbose_name='ortg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='ppg',
            field=models.FloatField(blank=True, verbose_name='ppg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='rpg',
            field=models.FloatField(blank=True, verbose_name='rpg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='spg',
            field=models.FloatField(blank=True, verbose_name='spg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='team',
            field=models.CharField(max_length=5, verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='toRate',
            field=models.FloatField(blank=True, verbose_name='to rate'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='topg',
            field=models.FloatField(blank=True, verbose_name='topg'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='trbP',
            field=models.FloatField(blank=True, verbose_name='trb%'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='ts',
            field=models.FloatField(blank=True, verbose_name='ts'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='usage',
            field=models.FloatField(blank=True, verbose_name='usage%'),
        ),
        migrations.AlterField(
            model_name='nba_players_21',
            name='viv',
            field=models.FloatField(blank=True, verbose_name='viv'),
        ),
    ]
