# Generated by Django 3.2.6 on 2021-12-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_nba_players_19'),
    ]

    operations = [
        migrations.CreateModel(
            name='nba_players_18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='full_name')),
                ('team', models.CharField(max_length=5, verbose_name='team')),
                ('position', models.CharField(max_length=15, verbose_name='position')),
                ('age', models.FloatField(blank=True, default=None, verbose_name='age')),
                ('gp', models.IntegerField(blank=True, default=None, verbose_name='gp')),
                ('mpg', models.FloatField(blank=True, default=None, verbose_name='mpg')),
                ('minP', models.FloatField(blank=True, default=None, verbose_name='min%')),
                ('usage', models.FloatField(blank=True, default=None, verbose_name='usage%')),
                ('toRate', models.FloatField(blank=True, default=None, verbose_name='to rate')),
                ('fta', models.IntegerField(blank=True, default=None, verbose_name='fta')),
                ('ftP', models.FloatField(blank=True, default=None, verbose_name='ft%')),
                ('fga2', models.IntegerField(blank=True, default=None, verbose_name='fga2')),
                ('fga2P', models.FloatField(blank=True, default=None, verbose_name='fga2%')),
                ('fga3', models.IntegerField(blank=True, default=None, verbose_name='fga3')),
                ('fga3P', models.FloatField(blank=True, default=None, verbose_name='fga3%')),
                ('efg', models.FloatField(blank=True, default=None, verbose_name='efg')),
                ('ts', models.FloatField(blank=True, default=None, verbose_name='ts')),
                ('ppg', models.FloatField(blank=True, default=None, verbose_name='ppg')),
                ('rpg', models.FloatField(blank=True, default=None, verbose_name='rpg')),
                ('trbP', models.FloatField(blank=True, default=None, verbose_name='trb%')),
                ('apg', models.FloatField(blank=True, default=None, verbose_name='apg')),
                ('astP', models.FloatField(blank=True, default=None, verbose_name='ast%')),
                ('spg', models.FloatField(blank=True, default=None, verbose_name='spg')),
                ('bpg', models.FloatField(blank=True, default=None, verbose_name='bpg')),
                ('topg', models.FloatField(blank=True, default=None, verbose_name='topg')),
                ('viv', models.FloatField(blank=True, default=None, verbose_name='viv')),
                ('ortg', models.FloatField(blank=True, default=None, verbose_name='ortg')),
                ('drtg', models.FloatField(blank=True, default=None, verbose_name='drtg')),
            ],
        ),
    ]
