# Generated by Django 3.2.6 on 2021-12-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_nba_players_18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nba_players_18',
            name='age',
            field=models.IntegerField(blank=True, default=None, verbose_name='age'),
        ),
    ]
